/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as NotLoginRouteImport } from './routes/notLogin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffWorkflowRouteImport } from './routes/staff/workflow'
import { Route as UserNewticketIndexRouteImport } from './routes/user/newticket/index'
import { Route as UserTicketsListRouteImport } from './routes/user/tickets/list'
import { Route as UserTicketsIdRouteImport } from './routes/user/tickets/$id'
import { Route as StaffWorkflowIdRouteImport } from './routes/staff/workflow_.$id'
import { Route as StaffTicketsListRouteImport } from './routes/staff/tickets/list'
import { Route as StaffTicketsAllRouteImport } from './routes/staff/tickets/all'
import { Route as StaffTicketsIdRouteImport } from './routes/staff/tickets/$id'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const NotLoginRoute = NotLoginRouteImport.update({
  id: '/notLogin',
  path: '/notLogin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffWorkflowRoute = StaffWorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => StaffRoute,
} as any)
const UserNewticketIndexRoute = UserNewticketIndexRouteImport.update({
  id: '/newticket/',
  path: '/newticket/',
  getParentRoute: () => UserRoute,
} as any)
const UserTicketsListRoute = UserTicketsListRouteImport.update({
  id: '/tickets/list',
  path: '/tickets/list',
  getParentRoute: () => UserRoute,
} as any)
const UserTicketsIdRoute = UserTicketsIdRouteImport.update({
  id: '/tickets/$id',
  path: '/tickets/$id',
  getParentRoute: () => UserRoute,
} as any)
const StaffWorkflowIdRoute = StaffWorkflowIdRouteImport.update({
  id: '/workflow_/$id',
  path: '/workflow/$id',
  getParentRoute: () => StaffRoute,
} as any)
const StaffTicketsListRoute = StaffTicketsListRouteImport.update({
  id: '/tickets/list',
  path: '/tickets/list',
  getParentRoute: () => StaffRoute,
} as any)
const StaffTicketsAllRoute = StaffTicketsAllRouteImport.update({
  id: '/tickets/all',
  path: '/tickets/all',
  getParentRoute: () => StaffRoute,
} as any)
const StaffTicketsIdRoute = StaffTicketsIdRouteImport.update({
  id: '/tickets/$id',
  path: '/tickets/$id',
  getParentRoute: () => StaffRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notLogin': typeof NotLoginRoute
  '/staff': typeof StaffRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/staff/workflow': typeof StaffWorkflowRoute
  '/staff/tickets/$id': typeof StaffTicketsIdRoute
  '/staff/tickets/all': typeof StaffTicketsAllRoute
  '/staff/tickets/list': typeof StaffTicketsListRoute
  '/staff/workflow/$id': typeof StaffWorkflowIdRoute
  '/user/tickets/$id': typeof UserTicketsIdRoute
  '/user/tickets/list': typeof UserTicketsListRoute
  '/user/newticket': typeof UserNewticketIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notLogin': typeof NotLoginRoute
  '/staff': typeof StaffRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/staff/workflow': typeof StaffWorkflowRoute
  '/staff/tickets/$id': typeof StaffTicketsIdRoute
  '/staff/tickets/all': typeof StaffTicketsAllRoute
  '/staff/tickets/list': typeof StaffTicketsListRoute
  '/staff/workflow/$id': typeof StaffWorkflowIdRoute
  '/user/tickets/$id': typeof UserTicketsIdRoute
  '/user/tickets/list': typeof UserTicketsListRoute
  '/user/newticket': typeof UserNewticketIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notLogin': typeof NotLoginRoute
  '/staff': typeof StaffRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/staff/workflow': typeof StaffWorkflowRoute
  '/staff/tickets/$id': typeof StaffTicketsIdRoute
  '/staff/tickets/all': typeof StaffTicketsAllRoute
  '/staff/tickets/list': typeof StaffTicketsListRoute
  '/staff/workflow_/$id': typeof StaffWorkflowIdRoute
  '/user/tickets/$id': typeof UserTicketsIdRoute
  '/user/tickets/list': typeof UserTicketsListRoute
  '/user/newticket/': typeof UserNewticketIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/notLogin'
    | '/staff'
    | '/user'
    | '/staff/workflow'
    | '/staff/tickets/$id'
    | '/staff/tickets/all'
    | '/staff/tickets/list'
    | '/staff/workflow/$id'
    | '/user/tickets/$id'
    | '/user/tickets/list'
    | '/user/newticket'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/notLogin'
    | '/staff'
    | '/user'
    | '/staff/workflow'
    | '/staff/tickets/$id'
    | '/staff/tickets/all'
    | '/staff/tickets/list'
    | '/staff/workflow/$id'
    | '/user/tickets/$id'
    | '/user/tickets/list'
    | '/user/newticket'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/notLogin'
    | '/staff'
    | '/user'
    | '/staff/workflow'
    | '/staff/tickets/$id'
    | '/staff/tickets/all'
    | '/staff/tickets/list'
    | '/staff/workflow_/$id'
    | '/user/tickets/$id'
    | '/user/tickets/list'
    | '/user/newticket/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  NotLoginRoute: typeof NotLoginRoute
  StaffRoute: typeof StaffRouteWithChildren
  UserRoute: typeof UserRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notLogin': {
      id: '/notLogin'
      path: '/notLogin'
      fullPath: '/notLogin'
      preLoaderRoute: typeof NotLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/workflow': {
      id: '/staff/workflow'
      path: '/workflow'
      fullPath: '/staff/workflow'
      preLoaderRoute: typeof StaffWorkflowRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/tickets/$id': {
      id: '/staff/tickets/$id'
      path: '/tickets/$id'
      fullPath: '/staff/tickets/$id'
      preLoaderRoute: typeof StaffTicketsIdRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/tickets/all': {
      id: '/staff/tickets/all'
      path: '/tickets/all'
      fullPath: '/staff/tickets/all'
      preLoaderRoute: typeof StaffTicketsAllRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/tickets/list': {
      id: '/staff/tickets/list'
      path: '/tickets/list'
      fullPath: '/staff/tickets/list'
      preLoaderRoute: typeof StaffTicketsListRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/workflow_/$id': {
      id: '/staff/workflow_/$id'
      path: '/workflow/$id'
      fullPath: '/staff/workflow/$id'
      preLoaderRoute: typeof StaffWorkflowIdRouteImport
      parentRoute: typeof StaffRoute
    }
    '/user/tickets/$id': {
      id: '/user/tickets/$id'
      path: '/tickets/$id'
      fullPath: '/user/tickets/$id'
      preLoaderRoute: typeof UserTicketsIdRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/tickets/list': {
      id: '/user/tickets/list'
      path: '/tickets/list'
      fullPath: '/user/tickets/list'
      preLoaderRoute: typeof UserTicketsListRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/newticket/': {
      id: '/user/newticket/'
      path: '/newticket'
      fullPath: '/user/newticket'
      preLoaderRoute: typeof UserNewticketIndexRouteImport
      parentRoute: typeof UserRoute
    }
  }
}

interface StaffRouteChildren {
  StaffWorkflowRoute: typeof StaffWorkflowRoute
  StaffTicketsIdRoute: typeof StaffTicketsIdRoute
  StaffTicketsAllRoute: typeof StaffTicketsAllRoute
  StaffTicketsListRoute: typeof StaffTicketsListRoute
  StaffWorkflowIdRoute: typeof StaffWorkflowIdRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffWorkflowRoute: StaffWorkflowRoute,
  StaffTicketsIdRoute: StaffTicketsIdRoute,
  StaffTicketsAllRoute: StaffTicketsAllRoute,
  StaffTicketsListRoute: StaffTicketsListRoute,
  StaffWorkflowIdRoute: StaffWorkflowIdRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

interface UserRouteChildren {
  UserTicketsIdRoute: typeof UserTicketsIdRoute
  UserTicketsListRoute: typeof UserTicketsListRoute
  UserNewticketIndexRoute: typeof UserNewticketIndexRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserTicketsIdRoute: UserTicketsIdRoute,
  UserTicketsListRoute: UserTicketsListRoute,
  UserNewticketIndexRoute: UserNewticketIndexRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  NotLoginRoute: NotLoginRoute,
  StaffRoute: StaffRouteWithChildren,
  UserRoute: UserRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
